TP-1123 Response pagination
GSA/touchpoints pull request #342
Opened 2020-11-05 14:46 UTC by aktfrikshun

This is first draft, no ajax
AJAX coming soon

2020-11-05 17:46 UTC, ryanwoldatwork requested changes

2020-11-05 17:46 UTC, ryanwoldatwork commented on app/assets/stylesheets/site.scss
> +nav {
Is this style intended to be scoped for the pagination?
I'm assuming `nav` is used elsewhere.

2020-11-05 17:46 UTC, ryanwoldatwork commented on app/models/submission.rb
> +  paginates_per 10
Sync with Natalie on this, but 100 at a time feels more reasonable than 10.

I'm thinking about if sorting submissions by `created_at DESC` would make more sense here than `ASC`. 
My thought is about having thousands of responses, and how to do I see latest easily? 
* look at first page of `DESC` sorted results
* click to last page and view `ASC` sorted results

2020-11-05 18:07 UTC, aktfrikshun commented
Makes sense on all points.  Ill have the ajax flavor soon.


On Thu, Nov 5, 2020, 12:46 PM Ryan Wold <notifications@github.com> wrote:

> *@ryanwoldatwork* requested changes on this pull request.
> ------------------------------
>
> In app/assets/stylesheets/site.scss
> <https://github.com/GSA/touchpoints/pull/342#discussion_r518239553>:
>
> > @@ -489,3 +489,9 @@ a.form-section-save {
>    border: none;
>    border-bottom: 1px solid black;
>  }
> +nav {
>
> Is this style intended to be scoped for the pagination?
> I'm assuming nav is used elsewhere.
> ------------------------------
>
> In app/models/submission.rb
> <https://github.com/GSA/touchpoints/pull/342#discussion_r518241689>:
>
> > @@ -9,6 +9,9 @@ class Submission < ApplicationRecord
>
>    scope :non_flagged, -> { where(flagged: false) }
>
> +  paginates_per 10
>
> Sync with Natalie on this, but 100 at a time feels more reasonable than 10.
>
> I'm thinking about if sorting submissions by created_at DESC would make
> more sense here than ASC.
> My thought is about having thousands of responses, and how to do I see
> latest easily?
>
>    - look at first page of DESC sorted results
>    - click to last page and view ASC sorted results
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GSA/touchpoints/pull/342#pullrequestreview-524511254>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMNDCO7SXKBM33NKRSS2O3SOLQHDANCNFSM4TLON3OA>
> .
>

2020-11-10 20:10 UTC, ryanwoldatwork approved these changes

2020-11-10 23:05 UTC, merged